component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/org/.*
- ./bin/org/exolab/.*
- ./bin/org/exolab/jms/.*
- ./bin/org/exolab/jms/administration/.*
- ./bin/org/exolab/jms/administration/net/.*
- ./bin/org/exolab/jms/authentication/.*
- ./bin/org/exolab/jms/client/.*
- ./bin/org/exolab/jms/client/net/.*
- ./bin/org/exolab/jms/common/.*
- ./bin/org/exolab/jms/common/security/.*
- ./bin/org/exolab/jms/common/threads/.*
- ./bin/org/exolab/jms/common/util/.*
- ./bin/org/exolab/jms/common/uuid/.*
- ./bin/org/exolab/jms/config/.*
- ./bin/org/exolab/jms/events/.*
- ./bin/org/exolab/jms/gc/.*
- ./bin/org/exolab/jms/jndi/.*
- ./bin/org/exolab/jms/lease/.*
- ./bin/org/exolab/jms/message/.*
- ./bin/org/exolab/jms/messagemgr/.*
- ./bin/org/exolab/jms/net/.*
- ./bin/org/exolab/jms/net/connector/.*
- ./bin/org/exolab/jms/net/http/.*
- ./bin/org/exolab/jms/net/http/connector/.*
- ./bin/org/exolab/jms/net/http/invoke/.*
- ./bin/org/exolab/jms/net/http/registry/.*
- ./bin/org/exolab/jms/net/invoke/.*
- ./bin/org/exolab/jms/net/jvm/.*
- ./bin/org/exolab/jms/net/multiplexer/.*
- ./bin/org/exolab/jms/net/orb/.*
- ./bin/org/exolab/jms/net/proxy/.*
- ./bin/org/exolab/jms/net/registry/.*
- ./bin/org/exolab/jms/net/rmi/.*
- ./bin/org/exolab/jms/net/rmi/connector/.*
- ./bin/org/exolab/jms/net/rmi/invoke/.*
- ./bin/org/exolab/jms/net/rmi/registry/.*
- ./bin/org/exolab/jms/net/socket/.*
- ./bin/org/exolab/jms/net/tcp/.*
- ./bin/org/exolab/jms/net/tcp/connector/.*
- ./bin/org/exolab/jms/net/tcp/invoke/.*
- ./bin/org/exolab/jms/net/tcp/registry/.*
- ./bin/org/exolab/jms/net/tunnel/.*
- ./bin/org/exolab/jms/net/uri/.*
- ./bin/org/exolab/jms/net/util/.*
- ./bin/org/exolab/jms/net/vm/.*
- ./bin/org/exolab/jms/net/vm/connector/.*
- ./bin/org/exolab/jms/net/vm/invoke/.*
- ./bin/org/exolab/jms/net/vm/registry/.*
- ./bin/org/exolab/jms/persistence/.*
- ./bin/org/exolab/jms/plugins/.*
- ./bin/org/exolab/jms/plugins/proxygen/.*
- ./bin/org/exolab/jms/scheduler/.*
- ./bin/org/exolab/jms/selector/.*
- ./bin/org/exolab/jms/selector/parser/.*
- ./bin/org/exolab/jms/server/.*
- ./bin/org/exolab/jms/server/net/.*
- ./bin/org/exolab/jms/service/.*
- ./bin/org/exolab/jms/tools/.*
- ./bin/org/exolab/jms/tools/admin/.*
- ./bin/org/exolab/jms/tools/db/.*
- ./bin/org/exolab/jms/tools/db/migration/.*
- ./bin/org/exolab/jms/tools/migration/.*
- ./bin/org/exolab/jms/tools/migration/master/.*
- ./bin/org/exolab/jms/tools/migration/proxy/.*
- ./bin/org/exolab/jms/tranlog/.*
- ./bin/org/exolab/jms/util/.*
- ./distribution/.*
- ./distribution/xdocs/.*
- ./distribution/xdocs/adminguide/.*
- ./distribution/xdocs/config/.*
- ./distribution/xdocs/devguide/.*
- ./distribution/xdocs/images/.*
- ./distribution/xdocs/usersguide/.*
- ./etc/.*
- ./lib/.*
- ./modules/.*
- ./modules/common/.*
- ./modules/examples/.*
- ./modules/jms/.*
- ./modules/jms/etc/.*
- ./modules/net/.*
- ./modules/proxygen-plugin/.*
- ./modules/tools/.*
- ./modules/tunnel/.*
- ./xdocs/.*
